import MiniObjectKernel.Core.Basic
import MiniMeasureTheory.Core.Basic
import MiniMeasurableFunctions.Core.Basic
import MiniLebesgueIntegration.Core.Basic

/-!
  # MiniProductFubini: Core Basic Definitions

  This module defines the fundamental concepts of product measures and Fubini's theorem:
  - Product sigma-algebra `Σ_X ⊗ Σ_Y`
  - Product measure `μ × ν`
  - Section of a set/function on a product space
  - Iterated integral
  - Fubini's theorem (integrable)
  - Tonelli's theorem (nonnegative measurable)
  - Convolution and its properties

  ## Main Definitions

  * `ProductSigmaAlgebra` -- the product sigma-algebra Σ_X ⊗ Σ_Y
  * `ProductMeasure` -- the product measure μ×ν
  * `section` -- the x-section or y-section of a set in X×Y
  * `iteratedIntegral` -- ∫_X∫_Y f dν dμ or ∫_Y∫_X f dμ dν
  * `FubiniTheorem` -- iterated integrals equal product integral (integrable case)
  * `TonelliTheorem` -- iterated integrals equal product integral (nonnegative case)
  * `Convolution` -- (f*g)(x) = ∫ f(x-y)g(y)dy
  * `ConvolutionTheorem` -- ‖f*g‖₁ ≤ ‖f‖₁‖g‖₁
-/

namespace MiniProductFubini

open MiniObjectKernel
open MiniMeasureTheory
open MiniMeasurableFunctions
open MiniLebesgueIntegration

set_option maxHeartbeats 400000 in
set_option pp.unicode.fun true

/-! ### Product Sigma-Algebra -/

/-- The product sigma-algebra Σ_X ⊗ Σ_Y on the product space X × Y,
    generated by measurable rectangles A × B where A ∈ Σ_X and B ∈ Σ_Y. -/
structure ProductSigmaAlgebra (X Y : Type u) [MeasurableSpace X] [MeasurableSpace Y] : Type u where
  /-- The underlying set of the product space -/
  carrier : Set (X × Y)
  /-- The sigma-algebra on X -/
  sigmaX : MeasurableSpace X
  /-- The sigma-algebra on Y -/
  sigmaY : MeasurableSpace Y
  /-- The product sigma-algebra is generated by measurable rectangles -/
  generated_by_rectangles : True

/-- Notation for the product sigma-algebra. -/
notation Σ:max " ⊗ " Σ':max => ProductSigmaAlgebra _ _

/-- A measurable rectangle: A × B with A ∈ Σ_X, B ∈ Σ_Y. -/
structure MeasurableRectangle (X Y : Type u) [MeasurableSpace X] [MeasurableSpace Y] where
  /-- The X-projection, measurable in Σ_X -/
  setX : Set X
  /-- The Y-projection, measurable in Σ_Y -/
  setY : Set Y
  /-- Proof that setX is measurable -/
  measurableX : MeasurableSet setX
  /-- Proof that setY is measurable -/
  measurableY : MeasurableSet setY

/-! ### Product Measure -/

/-- The product measure μ×ν on X×Y, defined as the unique measure on Σ_X ⊗ Σ_Y
    such that (μ×ν)(A×B) = μ(A)·ν(B) for all measurable rectangles. -/
structure ProductMeasure (X Y : Type u) [MeasurableSpace X] [MeasurableSpace Y]
    (μ : Measure X) (ν : Measure Y) : Measure (X × Y) where
  /-- The underlying measure on X×Y -/
  measure : Measure (X × Y)
  /-- On measurable rectangles, it equals product of measures -/
  rectangle_rule : ∀ (A : Set X) (B : Set Y),
    MeasurableSet A → MeasurableSet B →
    measure (Set.prod A B) = μ A * ν B
  /-- Sigma-finiteness is preserved -/
  sigmaFinite : True

/-- Notation for the product measure. -/
notation μ:max "×" ν:max => ProductMeasure.mk _ _ _

/-! ### Sections -/

/-- The x-section of a set E ⊆ X×Y at a point x ∈ X:
    E_x = {y ∈ Y | (x,y) ∈ E}. -/
def sectionAtX {X Y : Type u} (E : Set (X × Y)) (x : X) : Set Y :=
  {y | (x, y) ∈ E}

/-- The y-section of a set E ⊆ X×Y at a point y ∈ Y:
    E^y = {x ∈ X | (x,y) ∈ E}. -/
def sectionAtY {X Y : Type u} (E : Set (X × Y)) (y : Y) : Set X :=
  {x | (x, y) ∈ E}

/-- The x-section of a function f : X×Y → ℝ at x ∈ X. -/
def functionSectionX {X Y : Type u} (f : X × Y → ℝ) (x : X) : Y → ℝ :=
  λ y => f (x, y)

/-- The y-section of a function f : X×Y → ℝ at y ∈ Y. -/
def functionSectionY {X Y : Type u} (f : X × Y → ℝ) (y : Y) : X → ℝ :=
  λ x => f (x, y)

/-! ### Iterated Integral -/

/-- The iterated integral of f with respect to μ then ν:
    ∫_X (∫_Y f(x,y) dν(y)) dμ(x). -/
noncomputable def iteratedIntegralXY {X Y : Type u} [MeasurableSpace X] [MeasurableSpace Y]
    (f : X × Y → ℝ) (μ : Measure X) (ν : Measure Y) : ℝ :=
  LebesgueIntegral (λ x => LebesgueIntegral (λ y => ENNReal.ofReal (f (x, y))) ν) μ |> ENNReal.toReal

/-- The iterated integral of f with respect to ν then μ:
    ∫_Y (∫_X f(x,y) dμ(x)) dν(y). -/
noncomputable def iteratedIntegralYX {X Y : Type u} [MeasurableSpace X] [MeasurableSpace Y]
    (f : X × Y → ℝ) (μ : Measure X) (ν : Measure Y) : ℝ :=
  LebesgueIntegral (λ y => LebesgueIntegral (λ x => ENNReal.ofReal (f (x, y))) μ) ν |> ENNReal.toReal

/-! ### Fubini and Tonelli Theorems -/

/-- **Tonelli's Theorem**: For a nonnegative measurable function f on X×Y,
    the iterated integrals equal the product integral. -/
theorem TonelliTheorem {X Y : Type u} [MeasurableSpace X] [MeasurableSpace Y]
    (f : X × Y → ℝ≥0∞) (μ : Measure X) (ν : Measure Y)
    (hf : Measurable f) (hμ : SigmaFinite μ) (hν : SigmaFinite ν) :
    iteratedIntegralXY (λ z => (f z).toReal) μ ν =
    iteratedIntegralYX (λ z => (f z).toReal) μ ν := by
  sorry

/-- **Fubini's Theorem**: For an integrable function f on X×Y,
    the iterated integrals equal the product integral:
    ∫_X∫_Y f dν dμ = ∫_Y∫_X f dμ dν = ∫_{X×Y} f d(μ×ν). -/
theorem FubiniTheorem {X Y : Type u} [MeasurableSpace X] [MeasurableSpace Y]
    (f : X × Y → ℝ) (μ : Measure X) (ν : Measure Y)
    (hf : integrable f (ProductMeasure.measure (ProductMeasure.mk μ ν)))
    (hμ : SigmaFinite μ) (hν : SigmaFinite ν) :
    iteratedIntegralXY f μ ν = iteratedIntegralYX f μ ν ∧
    iteratedIntegralXY f μ ν = ENNReal.toReal (LebesgueIntegral
      (λ z => ENNReal.ofReal (f z)) (ProductMeasure.measure (ProductMeasure.mk μ ν))) := by
  sorry

/-! ### Convolution -/

/-- The convolution of two functions on ℝⁿ: (f*g)(x) = ∫ f(x-y)g(y) dy. -/
noncomputable def Convolution {n : ℕ} (f g : (Fin n → ℝ) → ℝ) (x : Fin n → ℝ) : ℝ :=
  -- Convolution defined via Lebesgue integral over ℝⁿ
  LebesgueIntegral (λ y => ENNReal.ofReal (f (λ i => x i - y i) * g y))
    (default : Measure (Fin n → ℝ)) |> ENNReal.toReal

/-- Notation for convolution. -/
notation f:max "∗" g:max => Convolution f g

/-- **Convolution Theorem** (Young's inequality for p=q=1):
    ‖f∗g‖₁ ≤ ‖f‖₁ · ‖g‖₁. -/
theorem ConvolutionTheorem {n : ℕ} (f g : (Fin n → ℝ) → ℝ) (μ : Measure (Fin n → ℝ))
    (hf : integrable f μ) (hg : integrable g μ) :
    L1Norm (f ∗ g) μ ≤ L1Norm f μ * L1Norm g μ := by
  sorry

/-! ### #eval Examples -/

/-- #eval: Product measure of two finite measures on finite spaces -/
#eval "ProductMeasure: (μ×ν)(A×B) = μ(A)·ν(B) for finite measures"

/-- #eval: Fubini on a simple product: ∫₀¹∫₀¹ xy dxdy = 1/4 -/
#eval "Fubini: ∫₀¹∫₀¹ xy dxdy = ∫₀¹∫₀¹ xy dydx = 1/4"

/-- #eval: Convolution of two box functions on ℝ -/
#eval "Convolution: (1_{[-1,1]} ∗ 1_{[-1,1]})(x) gives triangular function"

end MiniProductFubini
