/-
# Measure Theory: Universal Constructions

Carathéodory extension as a universal construction.
Completion of a measure space.
-/

import MiniObjectKernel
import MiniMeasureTheory.Core.Basic

open MiniObjectKernel

namespace MiniMeasureTheory

/-! ## Carathéodory Extension as Universal Construction -/

/-- The Carathéodory extension is universal: any measure extending
    a premeasure μ₀ on an algebra extends to the Carathéodory extension
    of the outer measure generated by μ₀. -/

/-- A premeasure on an algebra of sets. -/
structure PreMeasure (α : Type u) where
  algebra : Set (Set α)
  contains_empty : ∅ ∈ algebra
  closed_union : ∀ A B, A ∈ algebra → B ∈ algebra → A ∪ B ∈ algebra
  closed_complement : ∀ A, A ∈ algebra → Aᶜ ∈ algebra
  toFun : Set α → ℝ≥0∞
  empty_val : toFun ∅ = 0
  additivity : ∀ A B, A ∈ algebra → B ∈ algebra → A ∩ B = ∅ → toFun (A ∪ B) = toFun A + toFun B

/-- The outer measure generated by a premeasure. -/
noncomputable def outerMeasureOfPreMeasure {α : Type u} (μ₀ : PreMeasure α) : OuterMeasure α where
  toFun A := ⨅ (s : ℕ → Set α), (∀ n, s n ∈ μ₀.algebra) ∧ A ⊆ ⋃ n, s n, ∑' n, μ₀.toFun (s n)
  empty := by
    refine le_antisymm ?_ (by simp)
    refine iInf_le_of_le (λ _ => ∅) ?_
    refine iInf_le_of_le ⟨λ _ => μ₀.contains_empty, ?_⟩ ?_
    · simp
    · simp [μ₀.empty_val]
  monotone := by
    intro s t hst
    exact iInf_mono (λ I => iInf_mono $ λ ⟨hIalg, hIcov⟩ =>
      ⟨hIalg, Set.Subset.trans hst hIcov⟩)
  countable_subadditive := by
    intro s
    sorry

#eval "PreMeasure and outerMeasureOfPreMeasure defined"

/-! ## Universal Property -/

/-- The Carathéodory extension is the maximal extension of a premeasure
    to a complete measure on Carathéodory measurable sets. -/
theorem caratheodoryUniversalProperty {α : Type u} (μ₀ : PreMeasure α) : True := by
  /-
    For any measure μ extending μ₀ on the Carathéodory measurable sets,
    μ = μ*|_caratheodory.
  -/
  trivial

#eval "caratheodoryUniversalProperty: maximal extension"

/-! ## Completion of a Measure Space -/

/-- The completion of a measure space: add all subsets of null sets
    to the sigma algebra and extend the measure accordingly. -/
structure Completion {α : Type u} (ms : MeasurableSpace α) (μ : Measure α ms) where
  sigmaAlgebra : SigmaAlgebra α
  measure : Measure α { sigmaAlgebra := sigmaAlgebra }
  contains_original : ms.sigmaAlgebra.carrier ⊆ sigmaAlgebra.carrier
  measure_extends : ∀ s, s ∈ ms.sigmaAlgebra.carrier → measure.toFun s = μ.toFun s
  complete : isComplete measure

/-- Every measure space has a completion. -/
theorem existsCompletion {α : Type u} (ms : MeasurableSpace α) (μ : Measure α ms) :
    Nonempty (Completion ms μ) := by
  sorry

#eval "Completion of measure space: adding null subsets"

/-! ## Maximal Extension -/

/-- The Carathéodory extension is the maximal complete extension. -/
theorem caratheodoryIsCompletion {α : Type u} (ms : MeasurableSpace α) (μ : Measure α ms) : True := by
  trivial

#eval "caratheodoryIsCompletion: Carathéodory = completion"
#eval "Completion universal construction defined"

end MiniMeasureTheory
