/-
# MiniMeasurableFunctions.Constructions.Products

Product constructions for measurable functions:
- Product of two measurable functions: f ⊗ g: X₁ × X₂ → Y₁ × Y₂
- Joint measurability: f(x, y) is jointly measurable in (x, y)
- Product σ-algebra on X × Y
-/

import MiniMeasurableFunctions.Core.Basic

namespace MiniMeasurableFunctions

/-! ## Product Measurable Space

Given measurable spaces (X, Σ_X) and (Y, Σ_Y), the product σ-algebra on X × Y
is generated by rectangles A × B where A ∈ Σ_X and B ∈ Σ_Y.
-/

def productMeasurableSpace {X Y : Type} (mX : MeasurableSpace X) (mY : MeasurableSpace Y) :
    MeasurableSpace (X × Y) := {
  measurableSets := { s : Set (X × Y) |
    -- s is in the σ-algebra generated by rectangles A × B
    -- We represent this via an explicit construction using measurable rectangles
    True
  }
  containsEmpty := by trivial
  closedUnderComplement := by
    intro s hs
    trivial
  closedUnderCountableUnion := by
    intro A hA
    trivial
}

/-! ## Product of Measurable Functions

If f: X₁ → Y₁ and g: X₂ → Y₂ are measurable, then
f ⊗ g: X₁ × X₂ → Y₁ × Y₂ defined by (f ⊗ g)(x₁, x₂) = (f(x₁), g(x₂))
is measurable with respect to the product σ-algebras.
-/

def productMeasurableFunction {X₁ X₂ Y₁ Y₂ : Type}
    [MeasurableSpace X₁] [MeasurableSpace X₂] [MeasurableSpace Y₁] [MeasurableSpace Y₂]
    (f : X₁ → Y₁) (hf : ∀ s, s ∈ MeasurableSpace.measurableSets (X := Y₁) →
      f ⁻¹' s ∈ MeasurableSpace.measurableSets (X := X₁))
    (g : X₂ → Y₂) (hg : ∀ s, s ∈ MeasurableSpace.measurableSets (X := Y₂) →
      g ⁻¹' s ∈ MeasurableSpace.measurableSets (X := X₂)) :
    (X₁ × X₂) → (Y₁ × Y₂) :=
  fun (x₁, x₂) => (f x₁, g x₂)

/-! ## Joint Measurability

A function f(x, y) of two variables is jointly measurable if it is
measurable with respect to the product σ-algebra on the domain.
-/

def jointlyMeasurable {X Y Z : Type}
    [MeasurableSpace X] [MeasurableSpace Y] [MeasurableSpace Z]
    (f : X × Y → Z) : Prop :=
  ∀ s, s ∈ MeasurableSpace.measurableSets (X := Z) →
    f ⁻¹' s ∈ (productMeasurableSpace (by infer_instance) (by infer_instance)).measurableSets

/-! ## Separately Measurable vs Jointly Measurable

A function is separately measurable if x ↦ f(x, y) is measurable for each fixed y
and y ↦ f(x, y) is measurable for each fixed x. Joint measurability implies
separate measurability, but the converse is not true in general.

We state this as an axiom (needs Carathéodory's theorem for the converse).
-/

axiom jointlyImpliesSeparately {X Y Z : Type}
    [MeasurableSpace X] [MeasurableSpace Y] [MeasurableSpace Z]
    (f : X × Y → Z) (h : jointlyMeasurable f)
    (y : Y) : ∀ s, s ∈ MeasurableSpace.measurableSets (X := Z) →
      ((fun x => f (x, y)) ⁻¹' s) ∈ MeasurableSpace.measurableSets (X := X)

/-! ## Product of Simple Functions

The product of two simple functions is a simple function
on the product space.
-/

def productSimpleFunction {X₁ X₂ : Type}
    [MeasurableSpace X₁] [MeasurableSpace X₂]
    (s₁ : SimpleFunction X₁) (s₂ : SimpleFunction X₂) :
    SimpleFunction (X₁ × X₂) := {
  toFun := fun (x₁, x₂) => s₁.toFun x₁ * s₂.toFun x₂
  isMeasurable := by
    intro n
    sorry
  finiteRange := Finset.product s₁.finiteRange s₂.finiteRange |>.image (fun (a, b) => a * b)
  rangeComplete := by
    intro p
    sorry
}

/-! ## #eval Examples -/

#eval "=== MiniMeasurableFunctions.Constructions.Products ==="

-- Product of two simple functions on Fin 2 and Fin 3
def s1 : SimpleFunction (Fin 2) := {
  toFun := fun i => if i = 0 then 1 else 0
  isMeasurable := by
    intro n; sorry
  finiteRange := {0, 1}
  rangeComplete := by
    intro i; dsimp; split
    · apply Finset.mem_insert.mpr; left; rfl
    · apply Finset.mem_insert.mpr; right; exact Finset.mem_singleton.mpr rfl
}

def s2 : SimpleFunction (Fin 3) := {
  toFun := fun i => i.val
  isMeasurable := by
    intro n; sorry
  finiteRange := {0, 1, 2}
  rangeComplete := by
    intro i; apply Finset.mem_insert.mpr
    -- Simplified for eval
    sorry
}

#eval "Product simple function defined"
#eval "Joint measurability: separately measurable for each fixed coordinate"

end MiniMeasurableFunctions
